{
 "title": "sh600198:大唐电信",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "股票价格",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "stock_current_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "股票价格",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stock_current_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "今日涨跌幅",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "stock_increase_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "今日涨跌幅",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stock_increase_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "交易量变化趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(stock_trade_volume_total{code=\"sh600198\"}[10m])",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "委比",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "stock_weibi_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "买一至买三之和",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "stock_last_buy_3_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "卖一至卖三之和",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "stock_last_sell_3_gauge{code=\"sh600198\"}",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "七日内相对于最大值跌幅",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "((stock_current_gauge{code=\"sh600198\"}-max_over_time(stock_current_gauge{code=\"sh600198\"}[7d]))/max_over_time(stock_current_gauge{code=\"sh600198\"}[7d]))*100",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  },
  {
   "title": "七日内相对于最小值涨幅",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "((stock_current_gauge{code=\"sh600198\"}-min_over_time(stock_current_gauge{code=\"sh600198\"}[7d]))/min_over_time(stock_current_gauge{code=\"sh600198\"}[7d]))*100",
     "legendFormat": "{{code}}: {{name}}"
    }
   ]
  }
 ]
}