apiVersion: apps/v1
kind: Deployment
metadata:
  name: dark
  labels:
    app: dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dark
  template:
    metadata:
      labels:
        app: dark
    spec:
      containers:
        - name: dark
          image: kphoen/dark:latest
          env:
            - name: GRAFANA_HOST
              value: http://dashboard.stockmonitor.info:8888
            - name: GRAFANA_TOKEN
              value: eyJrIjoiSEZhQm5HQ0ZqdHJTa0hnMGRYQTNnNHhTWWl4Z2xQWXMiLCJuIjoiZGFyayIsImlkIjoxfQ==
      volumes:
        - name: dark-tokens
          secret:
            secretName: dark-tokens